---
driver:
  name: docker

platforms:
  - name: cl-arch
    image: archlinux:latest
    pre_build_image: true
    command: /sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp

  - name: cl-ubuntu
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    command: /sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      cl-arch:
        # arch's python is /usr/bin/python
        ansible_python_interpreter: /usr/bin/python3
  config_options:
    defaults:
      stdout_callback: default
      callback_result_format: yaml

verifier:
  name: ansible
